### ISSUE TITLE
Data access and visualisation

### ISSUE THREAD

**Issue by jevanilla** [oceanhackweek/ohw23_proj_fancymoorings#1]
- [ ] Develop script for accessing data

**Comment by jevanilla** [comment]
https://catalogue.cioospacific.ca/dataset/ca-cioos_82656721-88e6-4543-90f1-edc35c0f42c9

**Comment by setht1** [comment]
Puget Sound Data: [https://nwem.apl.washington.edu/erddap/index.html]
ORCA1 - Twanoh is a solid buoy for looking at data
