### ISSUE TITLE
Webpage architecture 

### ISSUE THREAD

**Issue by jevanilla** [oceanhackweek/ohw23_proj_fancymoorings#2]
Work on building the github page to host the mooring data

**Comment by schckngs** [comment]
We have a live page here: https://oceanhackweek.org/ohw23_proj_fancymoorings/
People can feel free to start editing the .md files that it draws from (you can see them referenced in the `toctree` at the bottom of those linked to this page so far :) )
Or maybe we want to start a folder with figures that folks can drop theirs in?

**Comment by jevanilla** [comment]
Goals

One tab for each of the mooring groups
Each person should push their finished notebooks this afternoon
Add project goals and some text
